// src/components/icons.jsx
// Re-exportamos de lucide-react para uso consistente
export {
    Sun,
    Moon,
    ShoppingCart,
    Menu,
    X,
    User,
    LogIn,
    UserPlus,
    Settings,
    Heart,
    Package,
    MapPin,
    Shield,
    LogOut,
    ChevronDown,
    Home,
    Info,
    Bell,
    Gift,
    ArrowRight,
    Search,
    Check,
    AlertCircle,
    Trash2,
    Clock,
    ExternalLink,
  } from 'lucide-react';